### ISSUE TITLE
Numbers Switch

### ISSUE THREAD

**Issue by jaikishantulswani** [Josue87/gotator#1]
@Josue87 It would be good if it have a switch to control the number mutations like if we want to mutate only 5 numbers like:
`
Gotator -sub domains.txt -perm permutations.txt -depth 3 -numbers +5 -t 200 > output.txt
`
One more things that gotator is not swapping the word from the subdomain list like:

Wordlist
`
one
`
domainlist

```
test.example.com
```

gotator mutate like 

```
test.example.com
one.test.example.com
one-test.example.com
onetest.example.com

```

Here I like to have mutations as below (give attention on **test** word)

```
one.test.example.com
test.one.example.com
onetest.example.com
one-test.example.com
testone.example.com
test-one.example.com
```

**Comment by Josue87** [comment]
Hello jaikishantulswani,

I was just working on something similar for mutations. On the number of iterations it seems correct and I have applied the change (except for indicating whether it is + or -, just a number and iterates up and down). I will evaluate the symbol with more time.

I have just made the changes. I am still testing the tool and checking what may be wrong or missing.

Thanks for your advice.

Best regards!

**Comment by jaikishantulswani** [comment]
@Josue87 thank you for this quick implementation but it is still skipping some mutations like this version of gotator doing mutations like :

**Currnet Gotator Version Mutations**
```
test.example.com
one.test.example.com
one-test.example.com
onetest.example.com
test.test.example.com
test-test.example.com
testtest.example.com
```

**Missing Mutations**

```
test.one.example.com
testone.example.com
test-one.example.com
```

**Comment by Josue87** [comment]
Yes, you are right.

Since it's a different mutation than the others and you need to extract the domain from the list, I'm thinking of putting it in as optional through an argument.

When I have time I will see it. Thanks

**Comment by jaikishantulswani** [comment]
@Josue87 thank you and waiting for that.

**Comment by Josue87** [comment]
Now you can make such permutations (flag **-md**).
And new conditions and filtering have been added.


I close the Issue. Thank you.

**Comment by jaikishantulswani** [comment]
@Josue87 thank you :)

**Comment by jaikishantulswani** [comment]
Hi @Josue87 After testing it, I found that it is still missing these combinations:

domainlist
```
xox.example.com
```
wordlist
```
one
1
```
My command to test ./gotator -sub domain.txt -perm wordlist.txt -md

it is missing 
`xox.xox`

and when I use command  gotator -sub domain.txt -perm wordlist.txt -md -depth 2

It is missing 
```
xox.xox
xox-xox
xoxxox
```

Thanks

**Comment by Josue87** [comment]
Indeed,

It has been developed in this way, to avoid duplicities and generate this type of permutations. Check in the Readme in the section Features the point dedicated to Control and reduce duplicates. 


Thanks.
