### ISSUE TITLE
flag provided but not defined

### ISSUE THREAD

**Issue by 0xSudip** [Josue87/gotator#13]
gotator -sub subdomains.txt -perm /usr/share/wordlists/dns/permutations_list.txt -depth 1 -numbers 10 -mindup -adv -md > permutations.txt                                                                                            2 ⨯
 When I run the above command it shows this -> flag provided but not defined: -mindup

**Comment by Josue87** [comment]
You probably have an older version, please try to update the tool.

Thank you.
