### ISSUE TITLE
Add one more option to silent the output

### ISSUE THREAD

**Issue by Dheerajmadhukar** [Josue87/gotator#4]
If possible please remove the Logo to pipe the command. Like -s/--silent for silent output.

**Comment by Josue87** [comment]
Hello, I have added the option >> **-silent**

However the output can be passed to the PIPE as only the results are written by the standard output. The banner and all other messages go to the error output.

The following commands give the same output (except that the banner is displayed in the terminal):

```
gotator -sub domains.txt -perm perm.txt -silent | wc -l
gotator -sub domains.txt -perm perm.txt | wc -l 
```
And the following also have the same output:

```
gotator -sub domains.txt -perm perm.txt -prefixes -silent | uniq > results.txt
gotator -sub domains.txt -perm perm.txt -prefixes | uniq > results.txt
```

Thanks.
