### ISSUE TITLE
no -adv flag 

### ISSUE THREAD

**Issue by MR-pentestGuy** [Josue87/gotator#6]
hey thank you for the tool when i downloaded from binary of go there is no -adv option present 

flag provided but not defined: -adv
Usage of gotator:
  -depth uint
        Specify the depth (Between 1 and 3) (default 1)
  -md
        Extract domains and subdomains from subdomains found in 'sub' list
  -mindup
        Set this flag to minimize duplicates. (For heavy workloads, it is recommended to activate this flag)
  -numbers uint
        Permute the numbers found in the list of permutations
  -perm string
        List of permutations (1 per line)
  -prefixes
        Adding gotator prefixes to permutations
  -silent
        Gotator banner is not displayed
  -sub string
        List of domains to be swapped (1 per line) [Required]
  -t uint
        Max Go routines (default 10)
  -version
        Show Gotator version

**Comment by Josue87** [comment]
Hello @MR-pentestGuy,

The flag `adv` is new. If you had installed the tool, try running the following command: `go get -u github.com/Josue87/gotator`.

Now you should see the flag.
