### ISSUE TITLE
Permutation with numbers

### ISSUE THREAD

**Issue by HolyBugx** [Josue87/gotator#9]
Hello,

I recently found an issue on Gotator, which is related to the numbering. Imagine, here is the list of my initial subdomains:

```
api.target.com
js.target.com
target.com
ws.target.com
www.target.com
```

I then ran the following command:

```
gotator -silent -sub subs.txt  -perm vhosts.txt -depth 1 -numbers 3 -mindup -adv -md >> permutation.txt
```

but the tool is unable to create the `js2.target.com`, which is pretty odd as I am using the numbers properly. Also, please note that this example subdomain was vulnerable to a subdomain takeover, which is not nice to miss.

Thanks in advance!

Kind regards,
HolyBugx

**Comment by Josue87** [comment]
Hello,

Without the list of permutations, I see that it's an expected behaviour. Check the point Permute numbers up and down, if subdomain or permutation doesn't contains number the tool doesn't add them (it only iterates around existing numbers).

Thank you
